#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if grep -rE "SERVICE_ID = '.*'|PUBLIC_KEY = '.*'|TEMPLATE_ID = '.*'" src/ --exclude-dir=node_modules; then
  echo "--------------------------------------------------------"
  echo "❌ ERROR: Llaves detectadas en el código (Hardcoded)."
  echo "Usa import.meta.env y mueve los valores al archivo .env"
  echo "--------------------------------------------------------"
  exit 1
fi