#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if grep -qE "SERVICE_ID = '.*'|PUBLIC_KEY = '.*'|TEMPLATE_ID = '.*'" src/**/*.{tsx,ts}; then
  echo "--------------------------------------------------------"
  echo "❌ ERROR DE SEGURIDAD: Llaves detectadas en el código."
  echo "Por favor, usa variables de entorno (.env)."
  echo "--------------------------------------------------------"
  exit 1
fi

pnpm test